version: "2.4"

services:
    bankService:
        image: rubismoreira/bankrubem1:5000
        ports:
          - "8089:80"
          
    accesscontrol:
        image: rubismoreira/co-accesscontrol
        ports:
          - "7771:80"
    
    db:
        image: "mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04"
        environment:
                MSSQL_SA_PASSWORD: "Dbpass12345678!"
                ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
