version: "2.4"

services:
    bankService:
        image: rubismoreira/bankrubem1:4001
        ports:
          - "8089:80"
          
    accesscontrol:
        image: rubismoreira/co-accesscontrol
        ports:
          - "7771:80"
    
    db:
        image: "microsoft/mssql-server-linux"
        environment:
                SA_PASSWORD: "Dbpass12345678!"
                ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
